services:

  nginx:
    restart: always
    container_name: nginx
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_network
    env_file:
      - .env
    volumes:
      - ./nginx/conf.d/temp/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot:v1.7.0
    user: "${UID}:${GID}"
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/letsecrypt.log:/var/log/letsencrypt/
    command: certonly --webroot -w /var/www/certbot -d ${DOMAIN} -d www.${DOMAIN} --email ${EMAIL} --agree-tos
    networks:
      - nginx_network
    depends_on:
      - nginx

networks:
  nginx_network:
    driver: bridge
    name: nginx_network
